name: docsenv

channels:
      - conda-forge

dependencies:
      - python=3.7
      - numpy
      - scipy 
      - cartopy>=0.17.0,<0.20|>=0.21;
      - matplotlib
      - h5py
      - conda-forge::sphinx-autodoc-typehints 
      - conda-forge::sphinx-gallery
